# Implementando uma rede Adaline do zero.

In [27]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

args = {
    'lr': 0.1,
    'min_error': 1e-20
}

In [28]:
train_df = pd.read_csv('train.csv')
train_df

,x1,x2,x3,x4,d
0,0.4329,-1.3719,0.7022,-0.8535,1.0
1,0.3024,0.2286,0.8630,2.7909,-1.0
2,0.1349,-0.6445,1.0530,0.5687,-1.0
3,0.3374,-1.7163,0.3670,-0.6283,-1.0
4,1.1434,-0.0485,0.6637,1.2606,1.0
5,1.3749,-0.5071,0.4464,1.3009,1.0
6,0.7221,-0.7587,0.7681,-0.5592,1.0
7,0.4403,-0.8072,0.5154,-0.3129,1.0
8,-0.5231,0.3548,0.2538,1.5776,-1.0
9,0.3255,-2.0000,0.7112,-1.1209,1.0


In [29]:
inputs = train_df.drop('d', axis=1) # axis 1 é coluna
inputs = np.array(train_df.drop('d', axis=1), dtype=float)
inputs.shape

(35, 4)

In [30]:
def get_normalization_params(data):
    return {
        'min': data.min(),
        'max': data.max()
    }

def normalize(data, norm_params=None):
    if norm_params is None:
        norm_params = get_normalization_params(data)
    
    return (data - norm_params['min']) / (norm_params['max'] - norm_params['min'])

norm_params = get_normalization_params(inputs) 


inputs = normalize(inputs)
inputs = np.insert(inputs, 0, -1, axis=1).transpose() # adiciona o limiar e transpõe a matriz

args['input_size'] = inputs.shape[0]
args['num_samples'] = inputs.shape[1]

inputs.shape

(5, 35)

In [31]:
outputs = train_df['d']
outputs = np.array(outputs, dtype=float)
outputs

array([ 1., -1., -1., -1.,  1.,  1.,  1.,  1., -1.,  1., -1., -1.,  1.,
        1., -1., -1.,  1., -1., -1.,  1.,  1., -1., -1.,  1., -1.,  1.,
       -1.,  1., -1.,  1.,  1.,  1., -1., -1., -1.])

## Inicializando os Pesos

In [32]:
weights = np.random.rand(args['input_size']).reshape(1, args['input_size'])
weights


array([[0.31717037, 0.60048273, 0.08603907, 0.4528594 , 0.61452053]])

## Erro Quadrático Médio

In [33]:
def mean_squared_error(desired_output, weights, inputs, num_samples):
    return np.sum((desired_output - np.dot(weights, inputs)) ** 2) / num_samples



### Treinamento

In [35]:
epochs = 0
while True:
    print('Initial weight vectors: ', weights)
    previous_eqm = mean_squared_error(outputs, weights, inputs, args['num_samples'])
    for i in range(args['num_samples']):
        activation_potential = np.dot(weights, inputs[:, i]) # agora, vamos linha a linha 
        weights = weights + args['lr'] * (outputs[i] - activation_potential) * inputs[:, i]
    current_eqm = mean_squared_error(outputs, weights, inputs, args['num_samples'])
    epochs += 1
    print('Epoch:', epochs, 'Error:', current_eqm)
    if abs(previous_eqm - current_eqm) < args['min_error']:
        print('Final weight vectors: ', weights)
        print('Converged')
        break
    

Initial weight vectors:  [[0.31717037 0.60048273 0.08603907 0.4528594  0.61452053]]
Epoch: 1 Error: 1.0442658961690947
Initial weight vectors:  [[ 0.6424285   0.51918413 -0.05489611  0.31303944  0.21771458]]
Epoch: 2 Error: 1.0174152773913177
Initial weight vectors:  [[ 0.57775335  0.59764669 -0.06229319  0.33815886  0.02634956]]
Epoch: 3 Error: 0.9954785252942504
Initial weight vectors:  [[ 0.52240063  0.67220633 -0.05870601  0.35827457 -0.14662797]]
Epoch: 4 Error: 0.97744054029817
Initial weight vectors:  [[ 0.47554602  0.74319164 -0.04570237  0.37387115 -0.30370766]]
Epoch: 5 Error: 0.9623603911557712
Initial weight vectors:  [[ 0.4360987   0.81104157 -0.02453715  0.38552969 -0.44688991]]
Epoch: 6 Error: 0.9495250418236292
Initial weight vectors:  [[ 0.40310691  0.8761391   0.00369562  0.39375716 -0.57791945]]
Epoch: 7 Error: 0.9383945999831576
Initial weight vectors:  [[ 0.37574054  0.93881821  0.03804206  0.39899577 -0.69831812]]
Epoch: 8 Error: 0.9285605353460082
Initial weight 

### Teste

In [36]:

print(norm_params)

test_df = pd.read_csv('test.csv')
test_inputs = np.array(test_df)
print(test_inputs.shape)
test_inputs = normalize(test_inputs, norm_params=norm_params)
print(test_inputs)
test_inputs = np.insert(test_inputs, 0, -1, axis=1).transpose()
test_inputs

{'min': np.float64(-3.2329), 'max': np.float64(5.8235)}
(15, 4)
[[0.4640144  0.43326267 0.40482973 0.74305464]
 [0.41689855 0.50970584 0.42753191 0.80253743]
 [0.42411996 0.25543262 0.42239742 0.36819266]
 [0.33910825 0.40880482 0.37938916 0.68952343]
 [0.37762245 0.32850802 0.42459476 0.55295702]
 [0.41098008 0.29871693 0.40531558 0.42807296]
 [0.39867939 0.57945762 0.43893821 0.73164834]
 [0.48393401 0.3120666  0.38423656 0.5321651 ]
 [0.45993993 0.47788304 0.47135727 0.72788304]
 [0.41284616 0.50401926 0.45880261 0.76744623]
 [0.36246191 0.12889228 0.42459476 0.28426306]
 [0.4011859  0.74751557 0.46480942 0.94806987]
 [0.33628152 0.50430635 0.41631333 0.71240228]
 [0.41284616 0.50401926 0.45880261 0.76744623]
 [0.53778543 0.26962148 0.44019699 0.41787024]]


array([[-1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ],
       [ 0.4640144 ,  0.41689855,  0.42411996,  0.33910825,  0.37762245,
         0.41098008,  0.39867939,  0.48393401,  0.45993993,  0.41284616,
         0.36246191,  0.4011859 ,  0.33628152,  0.41284616,  0.53778543],
       [ 0.43326267,  0.50970584,  0.25543262,  0.40880482,  0.32850802,
         0.29871693,  0.57945762,  0.3120666 ,  0.47788304,  0.50401926,
         0.12889228,  0.74751557,  0.50430635,  0.50401926,  0.26962148],
       [ 0.40482973,  0.42753191,  0.42239742,  0.37938916,  0.42459476,
         0.40531558,  0.43893821,  0.38423656,  0.47135727,  0.45880261,
         0.42459476,  0.46480942,  0.41631333,  0.45880261,  0.44019699],
       [ 0.74305464,  0.80253743,  0.36819266,  0.68952343,  0.55295702,
         0.42807296,  0.73164834,  0.5321651 , 

In [37]:
for i in range(test_df.shape[0]):
    print(f'Class {i}:', 1 if np.dot(weights, inputs[:, i]) > 0 else -1)


Class 0: 1
Class 1: -1
Class 2: -1
Class 3: 1
Class 4: 1
Class 5: 1
Class 6: 1
Class 7: 1
Class 8: -1
Class 9: 1
Class 10: 1
Class 11: -1
Class 12: 1
Class 13: 1
Class 14: -1
